pipeline {
    agent any
    
    environment {
        FRONTEND_IMAGE = 'xela146/tutor-front:latest'
        BACKEND_IMAGE = 'xela146/tutor-back:latest'
    }

  stages {
    stage('Build Backend') {
      steps {
          sh 'docker build -t $BACKEND_IMAGE .'
      }
    }

    stage('Test Backend') {
      steps {
        script {
            sh 'docker run $BACKEND_IMAGE npm test'
        }
      }
    }

    stage('Push Backend Image') {
      when {
        branch 'main'
      }
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
            sh "docker push $BACKEND_IMAGE"
          }
        }
      }
    }

    // stage('Deploy') {
    //   when {
    //     branch 'main'
    //   }
    //   steps {
    //     git(url: 'git@github.com:adtrahan146/tutor-centre-backend.git', credentialsId:'githubCreds', branch: 'main')
    //     dir('repo-containing-docker-compose') {
    //       withDockerRegistry([credentialsId: 'dockerhub-credentials', url: 'https://index.docker.io/v1/']) {
    //         sh 'docker-compose pull'
    //         sh 'docker-compose up -d'
    //       }
    //     }
    //   }
    // }
  }
}
